# Generated by Django 5.1 on 2025-02-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TaskApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="role",
            name="title",
        ),
        migrations.AddField(
            model_name="role",
            name="email",
            field=models.EmailField(default="", max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name="role",
            name="role_name",
            field=models.CharField(default="", max_length=30),
        ),
    ]
